import { useEffect, useState } from "react";
import PageWeather from "../components/PageWeather";

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [cities, setCities] = useState();
  const [selectedCity, setSelectedCity] = useState("London");
  const [weather, setWeather] = useState();
  const handleClick = (name) => {
    setSelectedCity(name);
  };

  useEffect(() => {
      fetch("https://countriesnow.space/api/v0.1/countries/capital/")
        .then((response) => response.json())
        .then((response) => {
          setCities(response);
        })
        .catch((err) => console.error(err));
      console.log(cities);
    }, []);
  

    
    useEffect(() => {
      fetch(
        `http://api.weatherstack.com/current?access_key=5c4d64c114b0322c2b3cb0ec4a031979&query=${selectedCity}`
      )
        .then((response) => response.json())
        .then((response) => {
          console.log(response);
          setWeather(response);
        })
        .catch((err) => console.error(err));
      console.log(weather);
    }, [selectedCity]);

    if (!cities || !weather) {
      return <div>Loading...</div>;
    }
    console.log(weather);

  return (
    <div>
      <Head>
        <title>wather App Ibrahim wais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='cointainer'>
      <PageWeather cities={cities} weather={weather} handleClick={handleClick} />
      </main>

     
    </div>
  )
}
